### ISSUE TITLE
IFlowFluid needs a new member that would allow you to "spawn" fluids

### ISSUE THREAD

**Issue by faceofcat** [BuildCraft/BuildCraftAPI#33]
**Buildcraft version:** 7.99.7
**Forge version:** 13.20.1.2386 (mc 1.11.2)

**Additional information:**
I'm trying to make a new type of pipe that would teleport items / fluids... for items it worked fine... but for fluids I couldn't find a way to spawn the fluid into the receiving pipe's center piece.

What would be cool for *IFlowFluid* to have is a method like:
```java
int pourIntoCenterPiece(FluidStack source, boolean simulate)
```
that would return the amount of the specified fluid that could be added to the center piece

**Comment by AlexIIL** [comment]
I don't think I'll use that method name, but yes, I missed this when adding an equivalent method to IFlowItem.

**Comment by AlexIIL** [comment]
I'll probably add a simulate param to ````IFlowItems.insertItemsForce```` as well, as that would probably be useful.

**Comment by AlexIIL** [comment]
Ok @faceofcat this should be implemented now, can you check to see if it's what you needed?

**Comment by faceofcat** [comment]
it fails to insert anything because of this test in PipeFluidFlow:
```java
        public int fill(FluidStack resource, boolean doFill) {
            if (this.getCurrentDirection().canInput() && PipeFlowFluids.this.pipe.isConnected(this.part.face) && resource != null) {
```
probably because the center piece of the target pipe is not connected in that direction... (sender pipe is always inserting from Down side)...

**Comment by AlexIIL** [comment]
...right, I forgot that that's not an internal skipping method :P

**Comment by AlexIIL** [comment]
I can't find your original request, but would
````java 
    @Nullable
    FluidStack extractFluidsForce(int min, int max, @Nullable EnumFacing section, boolean simulate);
````
be useful for fixing the fluid teleport pipes don't always extract all fluids if the destination is full bug?

**Comment by faceofcat** [comment]
the latest problem is that I use this event on the sender pipe:
```kotlin
        @PipeEventHandler
        fun onReachCenter(ev: PipeEventFluid.OnMoveToCentre) {
```
and the problem with that is that when the receiver pipe is full the sender pipe will fill up its center and not receive any more fluid... so that event is either not fired anymore, or comes with 0 amounts (can't remember)

last time we talked about this you said something about adding a new event for handling fluid in center piece... or something like that...

**Comment by AlexIIL** [comment]
I think this might be simpler (as otherwise I have to fire an event every tick for every pipe):

Add:
````kotlin
@PipeEventHandler
fun checkSides(ev: PipEventFluid.SideCheck) {
    ev.disallowAll() // Don't let fluids escape from the pipe, or the center of the pipe.
}
````
And:
````kotlin
fun onTick() {
    var max: Int
    max = getAmountThatReceiverCanReceive() // However you actually do this
    if (max > 0) {
        sendToReceiver(getFluidFlow().extractFluidsForce(0, max, null, false))
    }
}
````

**Comment by faceofcat** [comment]
sure... that would work... :)

is the 'extractFluidsForce' already in?

**Comment by AlexIIL** [comment]
not yet, I'm just evaluating how best to do it :)

**Comment by AlexIIL** [comment]
Pushed in https://github.com/BuildCraft/BuildCraftAPI/commit/a2f766271baf2e40d46d07df31edfe0cbb271015 and https://github.com/BuildCraft/BuildCraft/commit/9aba502a87b4ab640a52a0ff114c516334491c62. Hopefully that solves that?

**Comment by faceofcat** [comment]
works fine now! thanks!!
