### ISSUE TITLE
The API names should be lowercase

### ISSUE THREAD

**Issue by AlexIIL** [BuildCraft/BuildCraftAPI#44]
See https://github.com/Railcraft/Railcraft/issues/1408.

**Comment by CovertJaguar** [comment]
I'm getting a lot of complaints about this, and I don't think Forge accepts them as is.

**Comment by AlexIIL** [comment]
Right sorry about that I had ignored this for a while :(

**Comment by AlexIIL** [comment]
Anyway this is fixed *in dev* and will be out with 7.99.21, whenever *that* is released.

**Comment by AlexIIL** [comment]
Ok it's been released now - let me know if it still doesn't work when you change the api names
