### ISSUE TITLE
Create the BuildCraftGuide with Patchouli 

### ISSUE THREAD

**Issue by ErythroCraft** [BuildCraft/BuildCraftAPI#47]
Hi.

You can faster update the BuildCraftGuide, if you use the Patchouli.

https://github.com/Vazkii/Patchouli

**Comment by AlexIIL** [comment]
Rewriting the guide contents for Patchouli would take *longer* than just continuing to use BuildCraft's own guide system. (Which is already ported to 1.16.x  *(privately)* - so there's no more time cost to be paid for continuing to use BC's system).
